from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path('timetable/<str:username>', views.timetableforuser, name='timetableforuser'),
    path("nastavnici", views.nastavnici_template, name='nastavnici_template'),
    path('unosobv/<str:user>', views.unos_obavestenja_form, name='unosobavestenja'),
    path("saveobavestenje", views.save_obavestenje, name='saveobavestenje'),
    path('izbornagrupa/<str:username>', views.izborna_grupa_form, name='izbornagrupa'),
    path("saveizbornagrupa/<str:username>", views.saveizbornagrupa, name='saveizbornagrupa'),
    path('izmenagrupe/<str:oznakaGrupe>', views.izmenaIzborneGrupe, name='izmenagrupe'),
    path("saveizmenagrupa", views.sacuvanaIzmenaGrupe, name='saveizmenagrupa'),
    path('izborgrupe/<str:studentUserName>', views.izborGrupe, name='izborgrupe'),
    path("sacuvajizborgrupe/<str:username>", views.sacuvajIzborGrupe, name='sacuvajizborgrupe'),
    path("<str:username>/ispisgrupa", views.ispisGrupa, name='ispisgrupa'),
    path('ispisgrupa/<str:grupaID>', views.ispisGrupaID, name='ispisgrupaID'),
    path('ispisTrenutnihGrupa/<str:username>/<str:grupaID>', views.ispisTrenutnihGrupa, name='ispisTrenutnihGrupa'),
    path('uploadslike/<str:studentUserName>', views.uploadSlike, name='uploadslike'),
    path('savesliku', views.savesliku, name='savesliku'),
    path('prikazpredmeta/<str:username>', views.predmeti_profesor, name='prikazpredmeta'),
    path('prikazgrupe/<str:username>/<str:grupaID>', views.grupe_sa_slikama, name='prikazgrupe'),
    path('prikazslike/<str:username>/<str:studentID>', views.prikaz_slike, name='prikazslike'),
    path('uploadkolokvijum/<str:username>', views.upload_kolokvijum, name='uploadkolokvijum'),
    path('savekolokvijum', views.savekolokvijum, name='savekolokvijum'),
    path('izmenicu_sam', views.izmenicu_sam, name='izmenicu_sam'),
    path('forma_ispravak/<str:broj_reda>', views.forma_ispravak, name='forma_ispravak'),
    path('slanje_mejla/<str:username>', views.slanje_mejla, name='slanje_mejla'),
    path('posalji_mejl', views.posalji_mejl, name='posalji_mejl'),
    path('logovanje', views.logovanje, name='logovanje'),
    path('pomocna', views.pomocna, name='pomocna'),
    path('pocetni_ekran/<str:username>', views.pocetni_ekran, name='pocetni_ekran'),
    path('raspored_nastave/<str:username>', views.raspored_nastave, name='raspored_nastave'),
    path('uploadraspored/<str:username>', views.upload_raspored, name='uploadraspored'),
    path('saveraspored', views.save_raspored, name='saveraspored'),
]